# Generated by Django 6.0.4 on 2026-06-11 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_seed_default_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'Dịch vụ', 'verbose_name_plural': 'Dịch vụ'},
        ),
        migrations.AlterModelOptions(
            name='serviceaddon',
            options={'ordering': ['name'], 'verbose_name': 'Dịch vụ thêm', 'verbose_name_plural': 'Dịch vụ thêm'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['name'], 'verbose_name': 'Danh mục dịch vụ', 'verbose_name_plural': 'Danh mục dịch vụ'},
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/main/', verbose_name='Ảnh chính'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.servicecategory', verbose_name='Danh mục'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='Thời gian thực hiện'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(default='💆', max_length=8, verbose_name='Biểu tượng'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Dịch vụ nổi bật'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=160, verbose_name='Tên dịch vụ'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Giá dịch vụ'),
        ),
        migrations.AlterField(
            model_name='serviceaddon',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='serviceaddon',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='serviceaddon',
            name='name',
            field=models.CharField(max_length=160, verbose_name='Tên menu thêm'),
        ),
        migrations.AlterField(
            model_name='serviceaddon',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Giá thêm'),
        ),
        migrations.AlterField(
            model_name='serviceaddon',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='services.service', verbose_name='Dịch vụ'),
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/gallery/', verbose_name='Hình ảnh chi tiết')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='Chú thích')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service', verbose_name='Dịch vụ')),
            ],
            options={
                'verbose_name': 'Hình ảnh dịch vụ',
                'verbose_name_plural': 'Hình ảnh dịch vụ',
                'ordering': ['id'],
            },
        ),
    ]
