# Generated by Django 6.0.4 on 2026-06-11 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('services', '0003_alter_service_options_alter_serviceaddon_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_date', '-booking_time'], 'verbose_name': 'Lịch đặt', 'verbose_name_plural': 'Lịch đặt'},
        ),
        migrations.AlterModelOptions(
            name='servicereview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Đánh giá dịch vụ', 'verbose_name_plural': 'Đánh giá dịch vụ'},
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Tiền mặt'), ('transfer', 'Chuyển khoản')], default='cash', max_length=20, verbose_name='Hình thức thanh toán'),
        ),
        migrations.AddField(
            model_name='booking',
            name='staff',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên phục vụ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='addons',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='services.serviceaddon', verbose_name='Dịch vụ thêm'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(verbose_name='Ngày đặt'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(verbose_name='Giờ đặt'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Họ tên'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='note',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.service', verbose_name='Dịch vụ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('completed', 'Hoàn tất'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng'),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='booking.booking', verbose_name='Lịch đặt'),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Nội dung đánh giá'),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày đánh giá'),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='rating',
            field=models.PositiveSmallIntegerField(verbose_name='Số sao'),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.service', verbose_name='Dịch vụ'),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng'),
        ),
    ]
