# Generated by Django 6.0.4 on 2026-06-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_options_alter_servicereview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('change_time', 'Muốn đổi thời gian'), ('personal_busy', 'Có việc bận cá nhân'), ('wrong_booking', 'Đặt nhầm dịch vụ/thời gian'), ('no_need', 'Không còn nhu cầu'), ('other', 'Lý do khác')], max_length=50, null=True, verbose_name='Lý do hủy'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancel_reason_other',
            field=models.TextField(blank=True, verbose_name='Lý do hủy khác'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hủy'),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_account_name',
            field=models.CharField(blank=True, max_length=160, verbose_name='Tên chủ tài khoản hoàn tiền'),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_account_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Số tài khoản hoàn tiền'),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_bank_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Ngân hàng hoàn tiền'),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(choices=[('none', 'Không cần hoàn tiền'), ('pending', 'Chờ admin hoàn tiền'), ('refunded', 'Đã hoàn tiền')], default='none', max_length=20, verbose_name='Trạng thái hoàn tiền'),
        ),
        migrations.AddField(
            model_name='booking',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hoàn tiền'),
        ),
    ]
