# Generated by Django 6.0.4 on 2026-06-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_cancel_reason_booking_cancel_reason_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='staff_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian phục vụ thành công'),
        ),
        migrations.AddField(
            model_name='booking',
            name='staff_reject_reason',
            field=models.TextField(blank=True, verbose_name='Lý do nhân viên từ chối'),
        ),
        migrations.AddField(
            model_name='booking',
            name='staff_rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian từ chối phục vụ'),
        ),
        migrations.AddField(
            model_name='booking',
            name='staff_service_status',
            field=models.CharField(choices=[('ready', 'Sẵn sàng'), ('serving', 'Đang phục vụ'), ('done', 'Đã phục vụ'), ('rejected', 'Từ chối phục vụ')], default='ready', max_length=20, verbose_name='Tình trạng phục vụ'),
        ),
        migrations.AddField(
            model_name='booking',
            name='staff_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian bắt đầu phục vụ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang xác nhận'), ('paid', 'Đã thanh toán'), ('confirmed', 'Đã xác nhận'), ('completed', 'Hoàn tất'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái duyệt'),
        ),
    ]
