# Generated by Django 6.0.4 on 2026-06-11 23:55

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_staff_completed_at_and_more'),
        ('services', '0003_alter_service_options_alter_serviceaddon_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicereview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Đánh giá dịch vụ', 'verbose_name_plural': 'Quản lý đánh giá dịch vụ'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('paid', 'Đã thanh toán'), ('confirmed', 'Đã được duyệt'), ('completed', 'Đã phục vụ'), ('missed', 'Bỏ sót'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái duyệt'),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Số sao'),
        ),
        migrations.AddConstraint(
            model_name='servicereview',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_from_1_to_5'),
        ),
    ]
