# Generated by Django 6.0.4 on 2026-06-20 01:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_servicereview_options_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên phòng')),
                ('capacity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Sức chứa')),
                ('status', models.CharField(choices=[('available', 'Sẵn sàng'), ('maintenance', 'Đang bảo trì'), ('inactive', 'Ngừng hoạt động')], default='available', max_length=20, verbose_name='Trạng thái')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Phòng',
                'verbose_name_plural': 'Quản lý phòng',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_count',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lượng khách'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking.room', verbose_name='Phòng phục vụ'),
        ),
    ]
