databases:
  - name: spa-booking-docker-db
    databaseName: spa_booking
    user: spa_booking_user
    plan: free
    region: singapore

services:
  - type: web
    name: spa-booking-docker
    runtime: docker
    plan: free
    region: singapore
    branch: main

    dockerfilePath: ./Dockerfile
    dockerContext: .

    healthCheckPath: /api/health/
    autoDeployTrigger: checksPass

    envVars:
      - key: SECRET_KEY
        generateValue: true

      - key: DEBUG
        value: "False"

      - key: SECURE_SSL_REDIRECT
        value: "True"

      - key: SESSION_COOKIE_SECURE
        value: "True"

      - key: CSRF_COOKIE_SECURE
        value: "True"

      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"

      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"

      - key: DATABASE_URL
        fromDatabase:
          name: spa-booking-docker-db
          property: connectionString
